### ISSUE TITLE
Cool. This is incomplete :)

### ISSUE THREAD

**Issue by jasoryeh** [Avicus/Website#1]
Basically unusable because it's missing *that* much stuff

**Comment by AustinLMayes** [comment]
I just pulled this repository on a new PC and set it up with a fresh ruby install. Everything worked fine. Please refrain from making nondescript issues. Feel free to make one with an actual issue and one of our maintainers will respond when they are free.

**Comment by jamesxsc** [comment]
oof

**Comment by jasoryeh** [comment]
Can you describe your exact setup procedure? #2
