### ISSUE TITLE
Types::SettingType Missing AND failed rails s

### ISSUE THREAD

**Issue by jasoryeh** [Avicus/Website#2]
Steps to reproduce:

API Java Classes
1. Git clone
3. bundle/bundle install
2. Modify config.yml
3. (Not documented) Modify database.yml
4. Rake graphql::generate

Testing via Rails s
1. Same steps as above (1-3)
2. rails s

Tested on:
1. Windows 10 w/ Ruby + Devkit 2.5.3.1 x64
2. Ubuntu on WSL w/ ruby v. 2.5.1, 2.5.3, 2.6.0-preview2
3. Ubuntu 16.04 LTS

Full errors on both: https://paste.pagodanetwork.com/jogozeyala.coffeescript

Further investigations:
1. Checked through config/application.rb and found a comment 
![image](https://user-images.githubusercontent.com/13290941/50319322-9c394c00-047b-11e9-916f-5a1cb541e4d8.png)
Tried it, still errors.
2. Found no 'Types' thing, even when using JetBrains RubyMine
3. Dara?
![image](https://user-images.githubusercontent.com/13290941/50319387-f9cd9880-047b-11e9-96a5-dcf340fbdf7a.png)

Other:
Either instructions were unclear, or I'm doing something wrong. Instructions have exactly five steps for both things the website can do.

**Comment by AustinLMayes** [comment]
Try w/ graphql 1.7.4

**Comment by jasoryeh** [comment]
https://paste.pagodanetwork.com/ewisebiveh.sql Same problem

**Comment by AustinLMayes** [comment]
That's a blazer error - contact them at https://github.com/ankane/blazer

**Comment by jasoryeh** [comment]
What about missing Types::SettingType
