### ISSUE TITLE
API Does not work

### ISSUE THREAD

**Issue by jasoryeh** [Avicus/Website#3]
Attempting to start the api or accessing the api:

With:
`rails api` shows a error

`rails s` shows a 404

Configuration is already set up.

Connecting through localhost:3000 and 3001

**Comment by AustinLMayes** [comment]
Please actually provide the errors if you expect us to be able to help.

**Comment by jasoryeh** [comment]
Errors: https://paste.pagodanetwork.com/cojutafima.hs

For `rails s` and `rails s -e production` it has the default 404 page with the defense screenshot

Screenshot for `rails api`: 
![image](https://user-images.githubusercontent.com/13290941/50380925-473d3780-062d-11e9-86e8-e00052c0f554.png)

**Comment by jasoryeh** [comment]
bump.
Any updates?

**Comment by jasoryeh** [comment]
If the information I provided is still not enough, after commenting out the conflicting haml lines, and running `rails api` it still sends me a 404. 

![image](https://user-images.githubusercontent.com/13290941/50944232-71239600-1444-11e9-9d6b-b16776841024.png)
^^ And thats on /api

**Comment by jasoryeh** [comment]
Actually, nevermind. I fixed it. See my fork.
